### ISSUE TITLE
Overriding default actions throws an error

### ISSUE THREAD

**Issue by ecerroni** [CinKon/vue-pell-editor#1]
While trying to override the default array of pell actions I'm getting an error after clicking the toolbar button.

Code:

```
{
   name: 'italic',
   result: () => window.pell.exec('italic')
},
```

Error:
```
Uncaught TypeError: Cannot read property 'exec' of undefined
    at HTMLButtonElement.result 
```

**Comment by DotCoyote** [comment]
That's because `pell` isn't available in the window-store. You CAN overwrite the default actions, but `window.pell`-commands won't work by now.

**Comment by DotCoyote** [comment]
It is now possible to use 

```javascript
{
   name: 'italic',
   result: () => window.pell.exec('italic')
},
```
