### ISSUE TITLE
Unknown plugin "@babel/plugin-syntax-dynamic-import"

### ISSUE THREAD

**Issue by zeidanbm** [CinKon/vue-pell-editor#2]
Thanks for the plugin, this saved me time as I was going to do that for my project. I do have a quick question as I still didn't dig deep with this but I hope I can modify it to upload an image easily! 

Anyways, the issue I encoutered is that the plugin complains about "Unknown plugin "@babel/plugin-syntax-dynamic-import" in your .bable rc file. I don't think you should include that in your plugin folder(probably only for development). I just removed it with some other files that are not necessary to resolve this. Maybe create a seperate branch for contribution/development and another just for production.

**Comment by DotCoyote** [comment]
You're absolutely right.
Fixed this with Version 0.1.1
